server:
  port: 8084
spring:
  application:
    name: orderConsumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?serverTimezone=Asia&useSSL=false&serverTimezone=UTC
    username: root
    password: 8zhixingye
  jackson:
    default-property-inclusion: non_null # JSON?????????
  redis:
    host: 192.168.93.132
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

